services:
  # --- API Backend (Fastify + Node) ---
  backend:
    build: ./backend
    container_name: crm_backend
    restart: always
    ports:
      # Host 3000 -> Container 3000
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    command: npm run dev

  # --- Frontend App (Next.js) ---
  frontend:
    build: ./frontend
    container_name: crm_frontend
    restart: always
    ports:
      # Host 3001 -> Container 3000 (Acessar no navegador via localhost:3001)
      - "3001:3000" 
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    environment:
      # Aponta para o backend na porta 3000
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    command: npm run dev